### PR TITLE
Upgrade package to support django 3.x

### PR DESCRIPTION
**Pull request by andy840119**
- change package version and fix some error

### CODE REVIEW

**Comment by andy840119** [comment]
I'm not sure
```
INSTALLED_APPS = (
    ...
    'dbview',
)
```
is still needed because it works fine without adding this.

**Comment by manuelnaranjo** [comment]
@andy840119 thanks for the contribution, to be honest I'm not using this at all anymore, do you want to take ownership?

**Comment by andy840119** [comment]
I can take the ownership.
But maybe i'll transfer this repo to my company's organization to maintain it.
Is that ok?

**Comment by manuelnaranjo** [comment]
Sure just tell me to whom

**Comment by andy840119** [comment]
Okey.
you can transfer to https://github.com/hardcoretech and out member can continuous maintain it 😄

**Comment by manuelnaranjo** [comment]
I need to make you collaborator and then you can do it, it tells me I don't
have permissions to create repos on your org
-----------------------------
Naranjo, Manuel Francisco

**Comment by andy840119** [comment]
I have no authorization to transfer this repo either 😮 
maybe just send the pull request to here in the future i guess 🤔

**Pull request merged**
